POST http://localhost:3000/signup
Content-Type: application/json

{
    "name": "Leandro",
    "email": "le.amaral@outlook.com",
    "password": "123456"
}

###

POST http://localhost:3000/login
Content-Type: application/json

{
    "email": "le.amaral@outlook.com",
    "password": "123456"
}

###

GET http://localhost:3000/tasks
Content-Type: application/json

###

GET http://localhost:3000/work-orders
Content-Type: application/json
